train_data_loader:
  batch_size: 256
  num_workers: 4
  shuffle: true
  pin_memory: true
  persistent_workers: false

val_data_loader:
  batch_size: 128
  num_workers: 4
  shuffle: false
  pin_memory: true
  persistent_workers: false
