dtype: float32
action:
  mode: limits
  output_min: -1.0
  output_max: 1.0
lowdim:
  mode: limits
  output_min: -1.0
  output_max: 1.0
rgb:
  mode: image
  input_min: 0.0
  input_max: 1.0
  output_min: -1.0
  output_max: 1.0
  mean: 0.5
  std: 0.28867513
keys: {}
